# Generated by Django 5.0.4 on 2024-07-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20)),
                ('jurusan', models.CharField(max_length=50)),
                ('tahun_masuk', models.IntegerField()),
            ],
        ),
    ]
